---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r libraries, message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(patchwork)
```



## Suma de Riemann.

La función del gráfico es:

$$
  f(x) = \left(\frac{x}{2} - 1.5\right)^3 + 2
$$


Fórmula de la Suma de Riemann de la derecha:

$$
\sum_{i=1}^{n} f(a+\Delta x \cdot i) \cdot \Delta x
$$



```{r, fig.height=3, fig.width = 7.5}
right_riemann_fun <- function(a, b, n) {
  f_x <- function(x) (((x/2)-1.5)^3)+2
  
  fx_df <- tibble(
    x = seq(from = 0.71, to = 6, length.out = 200),
    f_x = f_x(x)
  )
  
  delta_x <- (b-a)/n
  i <- seq(from = 1, to = n, length.out = n)
  
  i_mid <- seq(from = 0, to = n-1, length.out = n)
  x_mid <- a + (delta_x*i_mid) + ((b-a)/(2*n))
  
  
  some_df <- tibble(
    delta_x,
    x = a + (delta_x*i),
    f_x = f_x(x)
  )
  
  some_df <- some_df %>% mutate(x_right = x+(x_mid-x))
  
  riemann_plot <- some_df %>% 
    ggplot(aes(y = f_x)) + 
    geom_vline(xintercept = 0, color = "lightgrey") + 
    geom_hline(yintercept = 0, color = "lightgrey") + 
    geom_col(
      aes(x = x_right),
      width = some_df$delta_x[1],
      color = "#5791b9",
      fill = "#abc6e1"
    ) + 
    geom_vline(xintercept = c(a, b), linetype = "dashed") + 
    geom_line(
      data = fx_df,
      aes(x = x, y = f_x),
      color = "#c63b42"
    ) + 
    list(
      if(n < 40) geom_point(aes(x = x))
    ) + 
    expand_limits(x = c(-0.5, 7), y = 0) + 
    scale_x_continuous(breaks = c(0, a, b), labels = c("0", "a", "b")) + 
    scale_y_continuous(breaks = 0) + 
    theme_light() + 
    theme(plot.title = element_text(hjust = 0.5),
          panel.grid = element_blank()) + 
    labs(x = NULL, y = NULL, title = paste0("n = ", n))
  
  return(riemann_plot)
}

area_under_curve <- 
  right_riemann_fun(a = 1, b = 5.72, n = 10) +
  right_riemann_fun(a = 1, b = 5.72, n = 55)
```


```{r, eval=FALSE, include=FALSE, echo=FALSE}
ggsave(filename = "area-under-curve-3.jpg", plot = area_under_curve,
       path = "img", height = 3, width = 7.5)
```




## Ejemplos Suma de Riemann.

```{r, fig.height=2.5, fig.width = (7.5)/2}
riemann_example_1 <- ggplot() + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_area(
    data = tibble(x = seq(from = 0, to = 2, length.out = 200), f_x = x^2),
    aes(x = x, y = f_x),
    fill = "#5791b9"
  ) + 
  geom_vline(xintercept = 2, linetype = "dashed") + 
  geom_line(
    data = tibble(x = seq(from = -0.5, to = 2.5, length.out = 200), f_x = x^2),
    aes(x = x, y = f_x),
    color = "#c63b42"
  ) + 
  annotate(geom = "text", x = 2.3, y = 4.2, label = "f(x) == x^2",
           parse = TRUE, color = "#c63b42") + 
  coord_cartesian(xlim = c(0, 2.5), ylim = c(0, 5.5)) + 
  scale_x_continuous(breaks = c(0, 2), labels = c("0", "b")) + 
  scale_y_continuous(breaks = 0) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(x = NULL, y = NULL)

riemann_example_1
```


```{r, eval=FALSE, include=FALSE, echo=FALSE}
ggsave(filename = "riemann_example-1.jpg", plot = riemann_example_1,
       path = "img", height = 2.5, width = 3.75)
```




```{r, fig.height=2.5, fig.width = (7.5)/2}
riemann_example_2_a <- ggplot() + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_area(
    data = tibble(x = seq(from = 0, to = 4, length.out = 200), f_x = x),
    aes(x = x, y = f_x),
    fill = "#5791b9"
  ) + 
  geom_vline(xintercept = 4, linetype = "dashed") + 
  geom_line(
    data = tibble(x = seq(from = -1, to = 6, length.out = 200), f_x = x),
    aes(x = x, y = f_x),
    color = "#c63b42"
  ) + 
  annotate(
    geom = "text", x = 5, y = 4, label = "f(x) = x", color = "#c63b42"
  ) + 
  coord_cartesian(xlim = c(0, 6), ylim = c(0, 5.5)) + 
  scale_x_continuous(breaks = c(0, 4), labels = c("0", "b")) + 
  scale_y_continuous(breaks = 0) + 
  theme_light() + 
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5)) + 
  labs(x = NULL, y = NULL, title = "(a)")

riemann_example_2_a
```



```{r, fig.height=2.5, fig.width = (7.5)/2}
riemann_example_2_b <- tibble(
  x = seq(from = 0, to = 3, length.out = 200), f_x = 1
  ) %>% 
  ggplot(aes(x = x, y = f_x)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_area(fill = "#5791b9") + 
  geom_vline(xintercept = 3, linetype = "dashed") + 
  geom_hline(yintercept = 1, color = "#c63b42") +
  annotate(
    geom = "text", x = 1.5, y = 1.2, label = "f(x) = 1", color = "#c63b42"
  ) + 
  coord_cartesian(xlim = c(0, 3.5), ylim = c(0, 2)) + 
  scale_x_continuous(breaks = c(0, 3), labels = c("0", "b")) + 
  scale_y_continuous(breaks = c(0, 1)) + 
  theme_light() + 
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5)) + 
  labs(x = NULL, y = NULL, title = "(b)")

riemann_example_2_b
```



```{r, fig.height=3, fig.width = 7.5}
riemann_example_2 <- (riemann_example_2_a+riemann_example_2_b)

riemann_example_2
```


```{r, eval=FALSE, include=FALSE, echo=FALSE}
ggsave(filename = "riemann_example-2.jpg", plot = riemann_example_2,
       path = "img", height = 3, width = 7.5)
```













































































