---
title: ''
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
```



```{r, message=FALSE, warning=FALSE}
library(tibble)
library(tidyr)
library(dplyr)
library(ggplot2)
```


#1. Ejemplo Probabilidades.

Función $N(r) = c \cdot \exp(-r^{2})$, para $c = 1$.

```{r, fig.height=3.5, fig.width=5}
darts_prob_exam <- tibble(
  r = seq(from = -5, to = 5, length = 200),
  N_r = exp(-(r^2))
) %>% 
  ggplot(aes(x = r, y = N_r)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_path() + 
  annotate(
    geom = "text",
    x = 1, y = 1.1,
    label = "N(r) == exp(-r^2)", parse = TRUE
  ) + 
  expand_limits(y = 1.3) + 
  coord_cartesian(xlim = c(-3, 3)) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(y = "N(r)", title = "N(r) para c = 1")

darts_prob_exam
```


```{r, eval=FALSE, include=FALSE}
ggsave(filename = "darts-prob-example-4.jpg", plot = darts_prob_exam,
       path = "img", width = 5, height = 3.5)
```



```{r, fig.height=3.5, fig.width=5}
darts_prob_exam_2 <- tibble(
  r = seq(from = -5, to = 5, length = 200),
  N_r = exp(-(r^2))
) %>% 
  ggplot(aes(x = r, y = N_r)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_area(
    data = tibble(
      r = seq(from = 0.5, to = 1, length = 200),
      N_r = exp(-(r^2))
    ),
    aes(x = r, y = N_r),
    fill = "#ea2627"
  ) + 
  geom_path() + 
  geom_rect(
    aes(xmin = 0.65, xmax = 0.9, ymin = 0, ymax = exp(-(0.9^2))),
    fill = "#7c7c7c"
  ) + 
  geom_segment(
    aes(x = 0, xend = 0.9, y = exp(-(0.9^2)), yend = exp(-(0.9^2))),
    linetype = "dashed"
  ) + 
  annotate(
    geom = "text",
    x = c(1, 0.775, 0.4), y = c(1.1, -0.05, 0.5),
    label = c("N(r) == exp(-r^2)", "dr", "r"), parse = TRUE,
    color = c("black", "#595959", "black")
  ) + 
  expand_limits(y = 1.3) + 
  coord_cartesian(xlim = c(-3, 3)) + 
  scale_x_continuous(
    breaks = c(-2, 0, 0.5, 1, 2),
    labels = expression(-2, 0, r[1], r[2], 2)
  ) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(y = "N(r)", title = "N(r) para c = 1")

darts_prob_exam_2
```



```{r, eval=FALSE, include=FALSE}
ggsave(filename = "darts-prob-example-5.jpg", plot = darts_prob_exam_2,
       path = "img", width = 5, height = 3.5)
```





Función $w(r) = (2 \pi r) \cdot (c \cdot \exp(-r^{2}))$.

```{r, fig.height=3.5, fig.width=5}
darts_prob_exam_3 <- tibble(
  r = seq(from = 0, to = 5, length.out = 200),
  w_r = (2*pi*r)*exp(-(r^2))
) %>% 
  ggplot(aes(x = r, y = w_r)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_path() + 
  annotate(
    geom = "text",
    x = 2, y = 2,
    label = "w(r) == (2*pi*r)%.%exp(-r^2)", parse = TRUE
  ) + 
  expand_limits(y = 3) + 
  coord_cartesian(xlim = c(0, 4)) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(y = "w(r)",
       title = expression(
         w(r)*" para "*list(c==1, r>=0)*" y "*r<infinity
        )
       )

darts_prob_exam_3
```



```{r, eval=FALSE, include=FALSE}
ggsave(filename = "darts-prob-example-6.jpg", plot = darts_prob_exam_3,
       path = "img", width = 5, height = 3.5)
```





















































































