---
title: ''
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 3.5, fig.width = 5)
```


```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r,fig.height=3.5, fig.width=5}
avg_val_ex_1 <- tibble(x = seq(from = -1, to = 1, length.out = 200),
       f_x = sqrt(1 - x^2)) %>% 
  ggplot(aes(x = x, y = f_x)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_path() + 
  geom_rect(aes(xmin = 0.4, xmax = 0.5, ymin = 0, ymax = sqrt(1-(0.5^2)))) + 
  annotate(
    geom = "text",
    x = c(0.45, 1), y = c(-0.05, 0.8),
    label = c("dx", "f(x) == sqrt(1 - x^2)"), parse = TRUE,
    color = c("#595959", "black")
  ) + 
  expand_limits(x = c(-1.25, 1.25), y = 1.5) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(x = NULL, y = NULL)

avg_val_ex_1
```


```{r, eval=FALSE, include=FALSE}
ggsave(filename = "avg-val-ex-1.jpg", plot = avg_val_ex_1, path = "img",
       width = 5, height = 3.5)
```





```{r,fig.height=3.5, fig.width=5}
avg_val_ex_2 <- tibble(x = seq(from = -1, to = 1, length.out = 200),
       f_x = sqrt(1 - x^2)) %>% 
  ggplot(aes(x = x, y = f_x)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_path() + 
  annotate(
    geom = "text", x = 1, y = 0.8,
    label = "f(x) == sqrt(1 - x^2)", parse = TRUE
  ) + 
  expand_limits(x = c(-1.25, 1.25), y = 1.5) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(x = NULL, y = NULL)

avg_val_ex_2
```


```{r, eval=FALSE, include=FALSE}
ggsave(filename = "avg-val-ex-2.jpg", plot = avg_val_ex_2, path = "img",
       width = 5, height = 3.5)
```




```{r, fig.width = 5, fig.height = 3.5}
cauldron_heat <- tibble(
  x = seq(from = -1, to = 1, length.out = 200),
  f_x = x^2
) %>% 
  ggplot(aes(x = x, y = f_x)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_path() + 
  geom_rect(aes(xmin = 0, xmax = sqrt(0.5), ymin = 0.5, ymax = 0.6)) + 
  geom_hline(yintercept = 1, linetype = "dashed") + 
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), linetype = "dashed") + 
  annotate(
    geom = "text",
    x = c(-1, 0.35, 0.85), y = c(0.5, 0.65, 0.55),
    label = c("f(x) == x^2", "x - 0", "dy"), parse = TRUE,
    color = c(rep("black", 2), "#595959"),
    size = 4.5
  ) + 
  expand_limits(x = c(-1.5, 1.5), y = 1.3) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(x = NULL, y = NULL)

cauldron_heat
```


```{r, eval=FALSE, include=FALSE}
ggsave(filename="cauldron-heat-2.jpg", plot = cauldron_heat, path = "img",
       width = 5, height = 3)
```





```{r, fig.width = 5, fig.height = 3.5}
prob_example <- tibble(
  x = seq(from = -1.05, to = 1.05, length.out = 200),
  f_x = 1 - (x^2)
) %>% 
  ggplot(aes(x = x, y = f_x)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_area(
    data = tibble(
      x = seq(from = 1/2, to = 1, length.out = 200), f_x = 1 - (x^2)
    ),
    aes(x = x, y = f_x)
  ) + 
  geom_path() + 
  annotate(
    geom = "text",
    x = c(0.6, 0.65), y = c(0.9, 0.25),
    label = c("f(x) == 1 - x^2", "x > over(1, 2)"),
    parse = TRUE,
    color = c("black", "#dbdbdb")
  ) + 
  scale_x_continuous(
    breaks = c(-1, 0, 0.5, 1),
    labels = c("-1", "0", "1/2", "1")
  ) + 
  coord_cartesian(ylim = c(0, 1.3)) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(x = NULL, y = NULL)

prob_example
```


```{r, eval=FALSE, include=FALSE}
ggsave(filename = "prob-example.jpg", plot = prob_example, path = "img",
       width = 5, height = 3)
```



















































