---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r, fig.width = 5, fig.height = 3}
R_2_vec_sp <- tibble(x = c(0, 3, exp(1)), y = c(0, 2, pi)) %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_vline(xintercept = c(exp(1), 3), color = "lightgrey", lty = 2) + 
  geom_hline(yintercept = c(2, pi), color = "lightgrey", lty = 2) + 
  geom_point() + 
  geom_segment(aes(x = 0, xend = 3, y = 0, yend = 2),
               arrow = arrow(length = unit(0.5, "cm"))) + 
  geom_segment(aes(x = 0, xend = exp(1), y = 0, yend = pi),
               arrow = arrow(length = unit(0.5, "cm"))) + 
  annotate(geom = "text", x = 0, y = 0.4,
           label = "group('(', list(0, 0), ')')", parse = TRUE) + 
  annotate(geom = "text", x = 2, y = 2.75,
           label = "group('(', list(e, pi), ')')", parse = TRUE) + 
  annotate(geom = "text", x = 2.5, y = 1.3,
           label = "group('(', list(3, 2), ')')", parse = TRUE) + 
  expand_limits(x = c(-1, 4), y = c(-1, 4)) + 
  scale_x_continuous(breaks = c(0, exp(1), 3), labels = expression(0, e, 3)) + 
  scale_y_continuous(breaks = c(0, 2, pi), labels = expression(0, 2, pi)) + 
  labs(x = "1er componente", y = "2do componente") + 
  theme_light() + 
  theme(panel.grid = element_blank(),
        axis.text = element_text(size = 11))
```

```{r}
ggsave(filename = "R_2_vec_sp.jpg", plot = R_2_vec_sp, path = "img/class-5",
       width = 5, height = 4)
```




## Clase 16. Mínimos Cuadrados.

```{r, fig.height=3.5, fig.width=5}
least_sq_df <- tibble(
  x = c(1:3),
  y_obs = c(1, rep(2, 2)),
  y_pred = (2/3) + ((1/2)*x),
  error = y_obs - y_pred
)

least_sq_3 <- least_sq_df %>%
  pivot_longer(cols = c(2, 3), names_to = "obs_pred", values_to = "values") %>%
  ggplot(aes(x = x, y = values)) + 
  geom_vline(xintercept = 0, color = "lightgrey") + 
  geom_hline(yintercept = 0, color = "lightgrey") + 
  geom_abline(slope = 1/2, intercept = 2/3) + 
  geom_segment(
    data = least_sq_df,
    aes(x = x, xend = x, y = y_obs, yend = y_pred),
    linetype = "dashed"
  ) + 
  geom_point(aes(color = obs_pred)) + 
  annotate(geom = "text", x = 3.4, y = 2.8,
           label = "hat(y) == over(2, 3) + over(1, 2)*x", parse = TRUE) + 
  expand_limits(x = c(0, 4), y = c(0, 3)) + 
  scale_color_manual(labels = c("Observados", "Predichos"),
                       values = c("#082cce", "#ce1508")) + 
  theme_light() + 
  theme(panel.grid =element_blank(),
        legend.position = c(0.19, 0.85),
        legend.background = element_rect(fill = "transparent")) + 
  labs(x = "x", y = "y", color = "Valores")

least_sq_3
```


```{r, eval=FALSE, include=FALSE}
ggsave(filename = "least-sq-3.jpg", plot = least_sq_3, path = "img/class-16",
       height = 3.5, width = 5)
```
















































